#!/bin/bash

# list files in current directory
echo "Current directory:"
ls -la

# list files in parent directory
echo "Parent directory:"
ls -la ..

# list files in /boot directory
echo "/boot directory:"
ls -la /boot
